steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --pull
      - -t
      - gcr.io/$PROJECT_ID/resumelang:$COMMIT_SHA
      - -t
      - gcr.io/$PROJECT_ID/resumelang:latest
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/resumelang:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/resumelang:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - resumelang
      - --image
      - gcr.io/$PROJECT_ID/resumelang:latest
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - '8080'
      - --set-env-vars
      - GOOGLE_CLOUD_PROJECT=$PROJECT_ID
      - --set-secrets
      - RL_GITHUB_CLIENT_ID=RL_GITHUB_CLIENT_ID:latest,RL_GITHUB_CLIENT_SECRET=RL_GITHUB_CLIENT_SECRET:latest,RL_AUTH_SECRET=RL_AUTH_SECRET:latest,GROQ_API_KEY=GROQ_API_KEY:latest

images:
  - gcr.io/$PROJECT_ID/resumelang:latest

options:
  logging: CLOUD_LOGGING_ONLY
